Repository Kernel360/E2E1-Anabada, pull requests merged in 2023-10, with the labels that each got.

#7 feat : DB 기반으로 Entity 설계 #5
  settings.gradle
  src/main/java/kr/kernel360/anabada/E2e1AnabadaApplication.java
  src/main/java/kr/kernel360/anabada/domain/category/entity/Category.java
  src/main/java/kr/kernel360/anabada/domain/comment/entity/Comment.java
  src/main/java/kr/kernel360/anabada/domain/faq/entity/Faq.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
  src/main/java/kr/kernel360/anabada/global/commons/entity/BaseEntity.java
  src/main/resources/application.yml
Labels: documentation

#33 불필요한 import 제거, 오타 수정, DTO 공백 라인 추가
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/resources/application.yml
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/trade/tradeRequestForm.html
  src/main/resources/templetes/.DS_Store
Labels: style

#34 feat : 회원 목록 조회 기능 develop에서 main으로 merge
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/resources/application.yml
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/trade/tradeRequestForm.html
  src/main/resources/templetes/.DS_Store
Labels: feat

#36 style : ResponseEntity 제네릭 명시, 롬복 어노테이션 적용
  .gitignore
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/resources/static/images/trade1.png
  src/main/resources/static/trade/tradeInfo.html
Labels: style

#38 feat : 회원 추가 수정 기능 추가
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/CreateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/CreateMemberResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
Labels: feat

#44 feat : 교환 등록
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/CreateTradeRequest.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeStatus.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeType.java
  src/main/resources/static/images/trade2.png
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/trade/tradeRequestForm.html
Labels: feat

#48 fix branch
  src/main/java/kr/kernel360/anabada/domain/faq/api/FaqController.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/CreateFaqRequest.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/CreateFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/UpdateFaqRequest.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/UpdateFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/entity/Faq.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
Labels: bug

#50 feat: 교환 등록 화면
  src/main/resources/static/trade/tradeCreateForm.html
Labels: feat

#51 Merge #50 into main
  src/main/resources/static/trade/tradeCreateForm.html
Labels: style

#52 feat : 유저 한명 조회, 삭제, 목록 조회 추가
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindMemberResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/resources/static/member/memberList.html
Labels: feat

#54 feat : faq 화면
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
Labels: feat

#57 feat : 카테고리 crud 기능 추가
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/CreateCategoryRequest.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/CreateCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/FindAllCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/FindCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/UpdateCategoryRequest.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/UpdateCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/entity/Category.java
  src/main/java/kr/kernel360/anabada/domain/category/repository/CategoryRepository.java
  src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
Labels: feat

#58 Merge #57 into main
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/CreateCategoryRequest.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/CreateCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/FindAllCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/FindCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/UpdateCategoryRequest.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/UpdateCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/entity/Category.java
  src/main/java/kr/kernel360/anabada/domain/category/repository/CategoryRepository.java
  src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
Labels: feat

#59 feat : 댓글 추가, 목록 조회 기능 구현 및 ERD 추가 내용 수정
  src/main/java/kr/kernel360/anabada/domain/category/dto/CreateCategoryRequest.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/FindCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/entity/Category.java
  src/main/java/kr/kernel360/anabada/domain/comment/api/CommentController.java
  src/main/java/kr/kernel360/anabada/domain/comment/dto/CreateCommentRequest.java
  src/main/java/kr/kernel360/anabada/domain/comment/dto/FindAllCommentDto.java
  src/main/java/kr/kernel360/anabada/domain/comment/dto/FindAllCommentResponse.java
  src/main/java/kr/kernel360/anabada/domain/comment/entity/Comment.java
  src/main/java/kr/kernel360/anabada/domain/comment/repository/CommentRepository.java
  src/main/java/kr/kernel360/anabada/domain/comment/service/CommentService.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/CreateTradeRequest.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/DeletedStatus.java
  src/main/resources/application.yml
Labels: feat, refactor, pair

#61 style : 화면 템플릿적용, FAQ 리팩토링
  src/main/java/kr/kernel360/anabada/domain/faq/api/FaqController.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/UpdateFaqRequest.java
  src/main/java/kr/kernel360/anabada/domain/faq/entity/Faq.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/include/sidebar.html
  src/main/resources/static/index.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
Labels: feat, style, refactor

#62 Merge #61 into main
  src/main/java/kr/kernel360/anabada/domain/faq/api/FaqController.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/UpdateFaqRequest.java
  src/main/java/kr/kernel360/anabada/domain/faq/entity/Faq.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/include/sidebar.html
  src/main/resources/static/index.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
Labels: feat, style

#63 refactor : trade, comment dto 구조 수정 / place 정보 추가
  src/main/java/kr/kernel360/anabada/domain/comment/dto/FindAllCommentResponse.java
  src/main/java/kr/kernel360/anabada/domain/comment/dto/FindCommentDto.java
  src/main/java/kr/kernel360/anabada/domain/comment/service/CommentService.java
  src/main/java/kr/kernel360/anabada/domain/place/dto/PlaceDto.java
  src/main/java/kr/kernel360/anabada/domain/place/entity/Place.java
  src/main/java/kr/kernel360/anabada/domain/place/repository/PlaceRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/CreateTradeRequest.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
Labels: refactor

#66 chore : BaseEntity 작성일자 컬럼명 변경
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/global/commons/entity/BaseEntity.java
Labels: chore

#64 feat : 메인화면 주소 변경 및 불필요 화면 템플릿 삭제
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/forms-editors.html
  src/main/resources/static/forms-elements.html
  src/main/resources/static/include/header.html
  src/main/resources/static/include/sidebar.html
  src/main/resources/static/index.html
  src/main/resources/static/tables-data.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
Labels: chore

#67 Develop #63 #64 #66 into main
  src/main/java/kr/kernel360/anabada/domain/comment/dto/FindAllCommentResponse.java
  src/main/java/kr/kernel360/anabada/domain/comment/dto/FindCommentDto.java
  src/main/java/kr/kernel360/anabada/domain/comment/service/CommentService.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
  src/main/java/kr/kernel360/anabada/domain/place/dto/PlaceDto.java
  src/main/java/kr/kernel360/anabada/domain/place/entity/Place.java
  src/main/java/kr/kernel360/anabada/domain/place/repository/PlaceRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/CreateTradeRequest.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/global/commons/entity/BaseEntity.java
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/forms-editors.html
  src/main/resources/static/forms-elements.html
  src/main/resources/static/include/header.html
  src/main/resources/static/include/sidebar.html
  src/main/resources/static/index.html
  src/main/resources/static/tables-data.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
Labels: feat, merge

#69 feat : 교환 요청 추가, 수정
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/CreateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindAllTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindAllTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferDto.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/UpdateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/UpdateTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
Labels: feat

#70 feat : 교환 요청 조회, 삭제 추가 및 TradeOffer, FindTradeDto 리팩토링
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/CreateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferDto.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeOfferStatus.java
  src/main/resources/application.yml
Labels: fix, feat, pair

#71 merge #69, #70 into main
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/CreateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindAllTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindAllTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferDto.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/UpdateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/UpdateTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeOfferStatus.java
  src/main/resources/application.yml
Labels: pair, merge

#73 refactor : TradeOfferController API endpoint 수정
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindAllTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/DeletedStatus.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeOfferSearchType.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeOfferStatus.java
  src/main/java/kr/kernel360/anabada/global/service/PaginationService.java
Labels: refactor
