Repository Kernel360/E2E1-Anabada, pull requests merged in 2023-11, with the labels that each got.

#75 Pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: chore

#76 chore : pr template 위치 변경
  .github/pull_request_template.md
Labels: chore

#77 Rename pull_request_template.md to PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#83 feat : access token 발급 및 로그아웃 구현, 화면 SPA 형식으로 변경 #79, #81, #82
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginRequest.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/TokenResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/MemberDetailService.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/CreateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtFilter.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtSecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/application.yml
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/assets/js/main.js
  src/main/resources/static/auth/login.html
  src/main/resources/static/error/pages-error-404.html
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/include/header.html
  src/main/resources/static/include/sidebar.html
  src/main/resources/static/index.html
  src/main/resources/static/js/commons.js
  src/main/resources/static/member/memberList.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
Labels: chore, feat, style

#84 merge : develop #83 into main
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginRequest.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/TokenResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/MemberDetailService.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/CreateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtFilter.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtSecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/application.yml
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/assets/js/main.js
  src/main/resources/static/auth/login.html
  src/main/resources/static/error/pages-error-404.html
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/include/header.html
  src/main/resources/static/include/sidebar.html
  src/main/resources/static/index.html
  src/main/resources/static/js/commons.js
  src/main/resources/static/member/memberList.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
Labels: fix, feat, style, merge

#86 merge : develop #83 into main
  src/main/java/kr/kernel360/anabada/domain/place/entity/Place.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/index.html
  src/main/resources/static/member/memberList.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/trade/tradeRequestForm.html
Labels: chore, feat, style

#87 fix : 화면에서 서버 호출 시 HTTP header에 토큰 정보 포함하도록 수정
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/kr/kernel360/anabada/domain/place/entity/Place.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/index.html
  src/main/resources/static/member/memberList.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/trade/tradeRequestForm.html
Labels: bug

#88 fix : 로그인 요청 api 인증 인가 없이 접근하도록 수정
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
Labels: fix

#89 merge : develop #88 into main
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
Labels: merge

#91 test : MemberService, MemberRepository, MemberController test 예시 추가
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/MemberDetailService.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/CreateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/test/java/kr/kernel360/anabada/domain/member/mock/api/MemberControllerMockTest.java
  src/test/java/kr/kernel360/anabada/domain/member/mock/service/MemberServiceMockTest.java
  src/test/java/kr/kernel360/anabada/domain/member/repository/MemberRepositoryTest.java
  src/test/java/kr/kernel360/anabada/domain/member/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: test

#95 bug : 닉네임, 이메일 중복체크
  src/main/resources/static/auth/signup.html
Labels: bug

#97 merge : #91, #95 into main
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/MemberDetailService.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/CreateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/static/auth/signup.html
  src/test/java/kr/kernel360/anabada/domain/member/mock/api/MemberControllerMockTest.java
  src/test/java/kr/kernel360/anabada/domain/member/mock/service/MemberServiceMockTest.java
  src/test/java/kr/kernel360/anabada/domain/member/repository/MemberRepositoryTest.java
  src/test/java/kr/kernel360/anabada/domain/member/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: merge

#99 merge : develop #98 into main
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/CreateTradeRequest.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/global/FileHandler.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
Labels: merge

#101 merge : develop #100 into main
  build.gradle
  src/main/java/kr/kernel360/anabada/E2e1AnabadaApplication.java
  src/main/java/kr/kernel360/anabada/domain/place/dto/PlaceDto.java
  src/main/java/kr/kernel360/anabada/domain/place/dto/PlaceResponse.java
  src/main/java/kr/kernel360/anabada/domain/place/dto/PlaceSearch.java
  src/main/java/kr/kernel360/anabada/global/api/KakaoFeignController.java
  src/main/java/kr/kernel360/anabada/global/client/KakaoFeignClient.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoPlaceResponse.java
  src/main/resources/application-API-KEY.yml
  src/main/resources/application.yml
  src/main/resources/static/auth/login.html
Labels: merge

#103 fix : tradeinfo에서 image file 안보이는 문제 해결
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/global/FileHandler.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/resources/application-API-KEY.yml
  src/main/resources/static/trade/tradeInfo.html
Labels: fix, pair

#104 merge : #103 into main
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/global/FileHandler.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/resources/application-API-KEY.yml
  src/main/resources/static/trade/tradeInfo.html
Labels: fix

#105 refactor : 메인화면 접속위치 수정
  src/main/java/kr/kernel360/anabada/global/api/KakaoFeignController.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/resources/static/auth/login.html
  src/main/resources/static/include/footer.html
  src/main/resources/static/include/header.html
  src/main/resources/static/index.html
  src/main/resources/static/main.html
Labels: style, refactor

#106 merge : develop #105 into main
  src/main/java/kr/kernel360/anabada/global/api/KakaoFeignController.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/resources/static/auth/login.html
  src/main/resources/static/include/footer.html
  src/main/resources/static/include/header.html
  src/main/resources/static/index.html
  src/main/resources/static/main.html
Labels: merge

#107 feat : 카테고리 화면 추가
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/FindAllCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/entity/Category.java
  src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/resources/static/category/categoryList.html
  src/main/resources/static/main.html
Labels: feat

#109 merge : develop #107 into main
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/category/dto/FindAllCategoryResponse.java
  src/main/java/kr/kernel360/anabada/domain/category/entity/Category.java
  src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/resources/static/category/categoryList.html
  src/main/resources/static/main.html
Labels: merge

#108 feat : 교환요청 별 이미지 경로 분할, 입력 수정 화면 validation 추가
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/global/FileHandler.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/trade/tradeCreateForm.html
Labels: chore, feat, style, refactor

#110 merge : #108 into main
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/global/FileHandler.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/trade/tradeCreateForm.html
Labels: merge

#111 fix : 엔티티 컬럼 길이 및 작성일시 날짜 포멧팅, 화면 유효성 검사 수정
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/entity/Faq.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
  src/main/java/kr/kernel360/anabada/global/utils/DateParser.java
  src/main/resources/static/category/categoryList.html
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/trade/tradeCreateForm.html
Labels: fix, feat, refactor

#112 merge : develop #111 into main
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/entity/Faq.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
  src/main/java/kr/kernel360/anabada/global/utils/DateParser.java
  src/main/resources/static/category/categoryList.html
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/trade/tradeCreateForm.html
Labels: merge

#114 feat : 관리자 통계 페이지 성별 및 연령대 별 도넛차트 추가
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberByAgeGroupResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberByGenderResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/resources/static/chart/adminChart.html
  src/main/resources/static/main.html
Labels: feat

#115 merge : #114 into main
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberByAgeGroupResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberByGenderResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/resources/static/chart/adminChart.html
  src/main/resources/static/main.html
Labels: feat, merge

#116 bug : 회원가입 성별선택 버그 수정
  src/main/resources/static/auth/signup.html
Labels: bug

#119 merge : develop #118 into main
  src/main/resources/static/chart/adminChart.html
Labels: merge

#120 feat : 거래 요청 화면
  src/main/resources/static/index.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeRequestForm.html
Labels: feat

#121 merge : develop #120 into main
  src/main/resources/static/index.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeRequestForm.html
Labels: merge

#122 refactor : 회원 식별자 jwt에서 가져오도록 수정, 이미지 디렉터리 추가
  src/main/java/kr/kernel360/anabada/domain/faq/dto/CreateFaqRequest.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/images/trade/.gitkeep
  src/main/resources/static/images/tradeOffer/.gitkeep
Labels: chore, refactor

#123 merge : develop #122 into main
  src/main/java/kr/kernel360/anabada/domain/faq/dto/CreateFaqRequest.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/images/trade/.gitkeep
  src/main/resources/static/images/tradeOffer/.gitkeep
Labels: merge

#124 refactor : 회원 식별자 jwt에서 가져오도록 전체 수정
  src/main/java/kr/kernel360/anabada/domain/comment/dto/CreateCommentRequest.java
  src/main/java/kr/kernel360/anabada/domain/comment/service/CommentService.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/CreateTradeRequest.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/CreateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/resources/static/trade/tradeCreateForm.html
Labels: refactor

#125 merge : develop #124 into main
  src/main/java/kr/kernel360/anabada/domain/comment/dto/CreateCommentRequest.java
  src/main/java/kr/kernel360/anabada/domain/comment/service/CommentService.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/CreateTradeRequest.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/CreateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/resources/static/trade/tradeCreateForm.html
Labels: merge

#126 feat : redis 설정 및 refreshToken 발급 구현
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/auth/dto/TokenResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/entity/RefreshToken.java
  src/main/java/kr/kernel360/anabada/global/config/RedisConfig.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/application.yml
  src/main/resources/static/auth/login.html
Labels: feat

#127 merge : develop #126 into main
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/auth/dto/TokenResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/entity/RefreshToken.java
  src/main/java/kr/kernel360/anabada/global/config/RedisConfig.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/application.yml
  src/main/resources/static/auth/login.html
Labels: merge

#129 merge : #128 into main
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/TokenDto.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
  src/main/java/kr/kernel360/anabada/global/config/RedisConfig.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtFilter.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/static/auth/login.html
  src/main/resources/static/auth/signup.html
  src/main/resources/static/index.html
Labels: merge

#130 feat : 소셜 로그인 skeleton, 마이 페이지 추가
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberByAgeGroupResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/place/dto/PlaceResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/global/api/KakaoController.java
  src/main/java/kr/kernel360/anabada/global/api/KakaoFeignController.java
  src/main/java/kr/kernel360/anabada/global/client/KakaoClient.java
  src/main/java/kr/kernel360/anabada/global/client/KakaoFeignClient.java
  src/main/java/kr/kernel360/anabada/global/config/KakaoFeignConfiguration.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoInfoResponse.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoMemberResponse.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoPlaceResponse.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoTokenResponse.java
  src/main/java/kr/kernel360/anabada/global/service/KakaoService.java
  src/main/resources/application-API-KEY.yml
  src/main/resources/application.yml
  src/main/resources/static/auth/login.html
  src/main/resources/static/auth/signup.html
  src/main/resources/static/include/header.html
  src/main/resources/static/index.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/test/java/kr/kernel360/anabada/domain/member/service/MemberServiceTest.java
Labels: feat

#131 merge : develop #130 into main
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberByAgeGroupResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/place/dto/PlaceResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/global/api/KakaoController.java
  src/main/java/kr/kernel360/anabada/global/api/KakaoFeignController.java
  src/main/java/kr/kernel360/anabada/global/client/KakaoClient.java
  src/main/java/kr/kernel360/anabada/global/client/KakaoFeignClient.java
  src/main/java/kr/kernel360/anabada/global/config/KakaoFeignConfiguration.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoInfoResponse.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoMemberResponse.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoPlaceResponse.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoTokenResponse.java
  src/main/java/kr/kernel360/anabada/global/service/KakaoService.java
  src/main/resources/application-API-KEY.yml
  src/main/resources/application.yml
  src/main/resources/static/auth/login.html
  src/main/resources/static/auth/signup.html
  src/main/resources/static/include/header.html
  src/main/resources/static/index.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/test/java/kr/kernel360/anabada/domain/member/service/MemberServiceTest.java
Labels: merge

#132 feat : 헤더에 회원정보 추가
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/resources/static/include/header.html
  src/main/resources/static/include/sidebar.html
  src/main/resources/static/index.html
  src/main/resources/static/main.html
  src/main/resources/static/member/memberInfo.html
Labels: feat

#133 merge : develop #132 into main
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/resources/static/include/header.html
  src/main/resources/static/include/sidebar.html
  src/main/resources/static/index.html
  src/main/resources/static/main.html
  src/main/resources/static/member/memberInfo.html
Labels: merge

#134 feat : my page 교환 요청 추가
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginRequest.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/TokenDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/global/client/KakaoClient.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeCreateForm.html
Labels: feat, merge

#135 merge : develop #134 into main
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginRequest.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/LoginResponse.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/TokenDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/global/client/KakaoClient.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeCreateForm.html
Labels: merge

#136 feat : 개인정보, 비밀번호 수정
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/resources/static/index.html
  src/main/resources/static/member/memberInfo.html
Labels: feat, refactor

#137 feat : 교환 등록의 카테고리 목록 조회 및 교환 목록 거래유형 뱃지 적용
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeList.html
Labels: feat, style

#138 merge : develop #136 into main
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/resources/static/index.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeList.html
Labels: merge

#139 feat : 권한 별 페이지 구현
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/category/repository/CategoryRepository.java
  src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindMemberResponse.java
  src/main/resources/static/admin/adminInfo.html
  src/main/resources/static/category/categoryList.html
  src/main/resources/static/chart/adminChart.html
  src/main/resources/static/include/header.html
  src/main/resources/static/index.html
  src/main/resources/static/main.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/member/memberList.html
Labels: fix, feat, style

#140 merge : #139 into main
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/category/repository/CategoryRepository.java
  src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindMemberResponse.java
  src/main/resources/static/admin/adminInfo.html
  src/main/resources/static/category/categoryList.html
  src/main/resources/static/chart/adminChart.html
  src/main/resources/static/include/header.html
  src/main/resources/static/index.html
  src/main/resources/static/main.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/member/memberList.html
Labels: merge

#141 feat : querydsl을 통한 tradeList 구분/카테고리 별 분류 기능 추가
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/TradeSearchCondition.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/resources/static/trade/tradeList.html
Labels: feat, refactor

#143 feat : 교환목록 페이징, 검색 기능 , 검색 count 쿼리 성능 최적화
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/TradeSearchCondition.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/global/config/QuerydslConfig.java
  src/main/resources/static/trade/tradeList.html
Labels: feat, refactor

#144 merge : develop #143 into main
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/TradeSearchCondition.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/global/config/QuerydslConfig.java
  src/main/resources/static/trade/tradeList.html
Labels: merge

#145 feat : FAQ 페이징, 검색 기능 구현
  src/main/java/kr/kernel360/anabada/domain/faq/api/FaqController.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FaqSearchCondition.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/global/client/KakaoClient.java
  src/main/java/kr/kernel360/anabada/global/config/KakaoFeignConfig.java
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/trade/tradeList.html
Labels: fix, feat

#146 merge : develop #145 into main
  src/main/java/kr/kernel360/anabada/domain/faq/api/FaqController.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FaqSearchCondition.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindAllFaqResponse.java
  src/main/java/kr/kernel360/anabada/domain/faq/dto/FindFaqDto.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepository.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/faq/repository/FaqRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/global/client/KakaoClient.java
  src/main/java/kr/kernel360/anabada/global/config/KakaoFeignConfig.java
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/trade/tradeList.html
Labels: merge

#147 feat : tradeOffer 로직 리팩토링, tradeOffer 목록화면, 상세화면 추가
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindAllTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferDto.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: feat

#148 merge : develop #147 into main
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindAllTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferDto.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepository.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: merge

#149 feat : 로그아웃 api 구현, 에러 페이지 연결
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/static/error/pages-error-403.html
  src/main/resources/static/index.html
Labels: fix, feat

#150 merge : develop #149 into main
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/static/error/pages-error-403.html
  src/main/resources/static/index.html
Labels: merge

#151 feat : TradeOffer 수락/ 삭제 기능 및 화면 구현
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/AcceptTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/UpdateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeOfferSearchType.java
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: feat

#152 merge : develop #151 into main
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/AcceptTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/UpdateTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/entity/TradeOffer.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeOfferSearchType.java
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: merge

#153 feat : 소셜 로그인, 관리자 페이지 리팩토링, 회원 닉네임 수정 기능 추가
  build.gradle
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/auth/dto/SignUpRequest.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/MemberDetailService.java
  src/main/java/kr/kernel360/anabada/domain/comment/service/CommentService.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/AgeGroupDto.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberByAgeGroupResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberByGenderResponse.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/GenderDto.java
  src/main/java/kr/kernel360/anabada/domain/member/dto/UpdateMemberRequest.java
  src/main/java/kr/kernel360/anabada/domain/member/entity/Member.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/oauth2/CustomOAuth2User.java
  src/main/java/kr/kernel360/anabada/domain/oauth2/OAuthAttributes.java
  src/main/java/kr/kernel360/anabada/domain/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/kr/kernel360/anabada/domain/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/kr/kernel360/anabada/domain/oauth2/memberinfo/KakaoOAuth2MemberInfo.java
  src/main/java/kr/kernel360/anabada/domain/oauth2/memberinfo/OAuth2MemberInfo.java
  src/main/java/kr/kernel360/anabada/domain/oauth2/service/CustomOAuth2MemberService.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/java/kr/kernel360/anabada/global/client/KakaoClient.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/PrincipalDetails.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/SocialProvider.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeOfferStatus.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoInfoResponse.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoMemberResponse.java
  src/main/java/kr/kernel360/anabada/global/dto/KakaoTokenResponse.java
  src/main/java/kr/kernel360/anabada/global/kakao/api/KakaoLocationController.java
  src/main/java/kr/kernel360/anabada/global/kakao/client/KakaoLocationClient.java
  src/main/java/kr/kernel360/anabada/global/kakao/dto/KakaoPlaceResponse.java
  src/main/java/kr/kernel360/anabada/global/kakao/service/KakaoLocationService.java
  src/main/java/kr/kernel360/anabada/global/service/KakaoService.java
  src/main/java/kr/kernel360/anabada/global/utils/AgeGroupParser.java
  src/main/java/kr/kernel360/anabada/global/utils/OrderByNull.java
  src/main/resources/application.yml
  src/main/resources/static/admin/adminInfo.html
  src/main/resources/static/auth/login.html
  src/main/resources/static/index.html
  src/main/resources/static/member/memberInfo.html
  src/test/java/kr/kernel360/anabada/domain/member/mock/service/MemberServiceMockTest.java
Labels: feat, style, refactor

#155 refactor : 리팩토링 및 도메인 별 BusinessException 적용
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/MemberDetailService.java
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
  src/main/java/kr/kernel360/anabada/domain/faq/api/FaqController.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/java/kr/kernel360/anabada/global/error/GlobalExceptionHandler.java
  src/main/java/kr/kernel360/anabada/global/error/code/AuthErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/CategoryErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/ErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/FaqErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/MemberErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/TokenErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/TradeErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/TradeOfferErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/dto/ErrorResponse.java
  src/main/java/kr/kernel360/anabada/global/error/exception/BusinessException.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtFilter.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/static/admin/adminInfo.html
  src/main/resources/static/auth/login.html
  src/main/resources/static/auth/signup.html
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/index.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: feat, refactor

#156 merge : #155 into main
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
  src/main/java/kr/kernel360/anabada/domain/auth/service/MemberDetailService.java
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
  src/main/java/kr/kernel360/anabada/domain/faq/api/FaqController.java
  src/main/java/kr/kernel360/anabada/domain/faq/service/FaqService.java
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/domain/member/service/MemberService.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/java/kr/kernel360/anabada/global/error/GlobalExceptionHandler.java
  src/main/java/kr/kernel360/anabada/global/error/code/AuthErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/CategoryErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/ErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/FaqErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/MemberErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/TokenErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/TradeErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/TradeOfferErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/dto/ErrorResponse.java
  src/main/java/kr/kernel360/anabada/global/error/exception/BusinessException.java
  src/main/java/kr/kernel360/anabada/global/jwt/JwtFilter.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/static/admin/adminInfo.html
  src/main/resources/static/auth/login.html
  src/main/resources/static/auth/signup.html
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/index.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: merge

#157 bug : 소셜로그인 회원가입
  src/main/java/kr/kernel360/anabada/domain/oauth2/OAuthAttributes.java
  src/main/resources/static/auth/login.html
Labels: bug

#158 merge : develop #157 into main
  src/main/java/kr/kernel360/anabada/domain/oauth2/OAuthAttributes.java
  src/main/resources/static/auth/login.html
Labels: merge

#160 feat : logback 추가
  .gitignore
  src/main/resources/logback-spring.xml
Labels: feat

#159 feat: tradeOffer, trade 화면
  src/main/java/kr/kernel360/anabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/CreateTradeRequest.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/entity/Trade.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferResponse.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: feat

#162 fix : 댓글, 교환요청, 교환
  .gitignore
  src/main/java/kr/kernel360/anabada/domain/comment/api/CommentController.java
  src/main/java/kr/kernel360/anabada/domain/comment/dto/FindCommentDto.java
  src/main/java/kr/kernel360/anabada/domain/comment/entity/Comment.java
  src/main/java/kr/kernel360/anabada/domain/comment/repository/CommentRepository.java
  src/main/java/kr/kernel360/anabada/domain/comment/service/CommentService.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferDto.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeOfferStatus.java
  src/main/java/kr/kernel360/anabada/global/error/code/CommentErrorCode.java
  src/main/resources/logback-spring.xml
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/include/header.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: fix, style

#163 merge : develop #162 into main
  src/main/java/kr/kernel360/anabada/domain/comment/api/CommentController.java
  src/main/java/kr/kernel360/anabada/domain/comment/dto/FindCommentDto.java
  src/main/java/kr/kernel360/anabada/domain/comment/entity/Comment.java
  src/main/java/kr/kernel360/anabada/domain/comment/repository/CommentRepository.java
  src/main/java/kr/kernel360/anabada/domain/comment/service/CommentService.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindTradeResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferDto.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/global/commons/domain/TradeOfferStatus.java
  src/main/java/kr/kernel360/anabada/global/error/code/CommentErrorCode.java
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/include/header.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: merge

#164 feat: trade 생성 및 조회 시 위치정보 적용
  src/main/java/kr/kernel360/anabada/domain/place/repository/PlaceRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/global/error/code/TradeErrorCode.java
  src/main/resources/static/trade/tradeList.html
Labels: feat

#165 merge : develop #164 into main
  src/main/java/kr/kernel360/anabada/domain/place/repository/PlaceRepository.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/global/error/code/TradeErrorCode.java
  src/main/resources/static/trade/tradeList.html
Labels: merge

#166 feat : 마이페이지
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindAllTradeOfferRequest.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/dto/FindTradeOfferDto.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/service/TradeOfferService.java
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: fix, feat

#170 feat : 관리자 API 접근 권한 설정
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/index.html
Labels: feat

#171 merge : main #160 into develop
  src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
  src/main/java/kr/kernel360/anabada/domain/member/api/MemberController.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/index.html
Labels: merge

#172 feat : kakao, trade 에러 코드 및 관리자 통계에 시도별 교환 추가
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberByGenderResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradesByStateResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/StateCountDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/global/error/code/KakaoErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/PlaceErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/TradeErrorCode.java
  src/main/java/kr/kernel360/anabada/global/kakao/service/KakaoLocationService.java
  src/main/resources/static/admin/adminInfo.html
  src/main/resources/static/assets/img/kakao-login-button.png
  src/main/resources/static/auth/login.html
Labels: feat

#173 merge : develop #172 into main
  src/main/java/kr/kernel360/anabada/domain/member/dto/FindAllMemberByGenderResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/FindAllTradesByStateResponse.java
  src/main/java/kr/kernel360/anabada/domain/trade/dto/StateCountDto.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryCustom.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/java/kr/kernel360/anabada/global/error/code/KakaoErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/PlaceErrorCode.java
  src/main/java/kr/kernel360/anabada/global/error/code/TradeErrorCode.java
  src/main/java/kr/kernel360/anabada/global/kakao/service/KakaoLocationService.java
  src/main/resources/static/admin/adminInfo.html
  src/main/resources/static/assets/img/kakao-login-button.png
  src/main/resources/static/auth/login.html
Labels: merge

#174 fix : 마이페이지 내가올린교환
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/resources/static/member/memberInfo.html
Labels: fix

#175 merge : develop #174 into main
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/trade/service/TradeService.java
  src/main/resources/static/member/memberInfo.html
Labels: fix

#186 fix : refreshToken Exception 반영 및 회원가입API 엔드포인트 변경
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/error/code/TokenErrorCode.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/static/auth/login.html
  src/main/resources/static/auth/signup.html
  src/main/resources/static/index.html
Labels: fix

#187 merge : develop #186 into main
  src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
  src/main/java/kr/kernel360/anabada/global/config/SecurityConfig.java
  src/main/java/kr/kernel360/anabada/global/error/code/TokenErrorCode.java
  src/main/java/kr/kernel360/anabada/global/jwt/TokenProvider.java
  src/main/resources/static/auth/login.html
  src/main/resources/static/auth/signup.html
  src/main/resources/static/index.html
Labels: merge

#190 style : 서비스 소개 작성
  src/main/resources/static/assets/img/main.png
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/include/header.html
  src/main/resources/static/index.html
  src/main/resources/static/main.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: fix, style

#191 merge : develop #190 into main
  src/main/resources/static/assets/img/main.png
  src/main/resources/static/faq/faqCreateForm.html
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/faq/faqList.html
  src/main/resources/static/faq/faqUpdateForm.html
  src/main/resources/static/include/header.html
  src/main/resources/static/index.html
  src/main/resources/static/main.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: merge

#194 bug : ec2 파일업로드 오류 문제로 인한 로그 추가
  src/main/java/kr/kernel360/anabada/global/FileHandler.java
Labels: bug

#195 chore : readme, feedback-form 추가
  .github/ISSUE_TEMPLATE/feedback-form.yml
  README.md
  src/main/resources/readme/Anabada ERD.png
  src/main/resources/readme/Anabada Github Flowchart.png
  src/main/resources/readme/Anabada System Architecture.png
  src/test/resources/config/application.yml
Labels: chore

#196 merge : develop #195 into main
  .github/ISSUE_TEMPLATE/feedback-form.yml
  README.md
  src/main/resources/readme/Anabada ERD.png
  src/main/resources/readme/Anabada Github Flowchart.png
  src/main/resources/readme/Anabada System Architecture.png
  src/test/resources/config/application.yml
Labels: merge

#211 bug : ec2 파일 업로드 오류
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/global/FileHandler.java
Labels: bug

#212 merge : develop #211 into main
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/global/FileHandler.java
Labels: merge

#213 feat : add image/trade, image/tradeOffer
  images/trade/.gitkeep
  images/tradeOffer/.gitkeep
Labels: feat

#214 merge : develop #213 into main
  images/trade/.gitkeep
  images/tradeOffer/.gitkeep
Labels: feat

#216 chore : 로그 및 이미지 저장 경로 수정
  .gitignore
  logs/.gitkeep
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/global/FileHandler.java
  src/main/resources/logback-spring.xml
Labels: chore

#215 chore : remove console log
  src/main/resources/static/index.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeCreateForm.html
  src/main/resources/static/trade/tradeInfo.html
  src/main/resources/static/trade/tradeList.html
  src/main/resources/static/tradeOffer/tradeOfferCreateForm.html
  src/main/resources/static/tradeOffer/tradeOfferInfo.html
  src/main/resources/static/tradeOffer/tradeOfferList.html
Labels: chore

#218 refactor : 위치 정보 캐시 적용, faq 수정 삭제 버튼 수정
  src/main/resources/static/faq/faqInfo.html
  src/main/resources/static/index.html
Labels: refactor

#219 fix : 버그 테스트 발견 버그 수정
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/resources/static/index.html
  src/main/resources/static/member/memberInfo.html
  src/main/resources/static/trade/tradeList.html
Labels: fix

#222 bug : 버그 테스트 발견 버그 수정 및 리팩토링
  src/main/java/kr/kernel360/anabada/domain/trade/api/TradeController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/api/TradeOfferController.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/global/FileHandler.java
  src/main/java/kr/kernel360/anabada/global/error/code/FileErrorCode.java
  src/main/resources/static/index.html
Labels: bug, refactor

#225 merge : #224 into main
  README.md
Labels: merge

#226 fix : 교환목록, 교환요청목록 정렬 조건
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
Labels: fix

#227 merge : develop #226 into main
  src/main/java/kr/kernel360/anabada/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/kr/kernel360/anabada/domain/tradeoffer/repository/TradeOfferRepositoryImpl.java
Labels: merge

#228 feat: categoryServiceTest 추가
  src/test/java/kr/kernel360/anabada/domain/category/service/CategoryServiceTest.java
Labels: test

#231 Update README.md
  README.md
Labels: merge
